project:
  type: website
  output-dir: docs

website:

  title: "<b>Home</b>"
  site-url: "https://vuqv.github.io/"
  description: "My blog"
  page-navigation: true
  reader-mode: true
  favicon: img/QV.png
  search: 
    location: navbar
    type: textbox

  navbar:
    search: true
    pinned: true
    right:
      - pages/news/index.qmd
      - pages/team/index.qmd
      - pages/publications/index.qmd
      - pages/tools/index.qmd
      - text: "**About me**"
        href: pages/about/index.qmd
      - icon: github
        href: https://github.com/vuqv
      - icon: twitter
        href: https://twitter.com/qvv5013

  page-footer:
    center:
      - text: "Copyright 2023, Quyen Vu"
        href: pages/about/index.qmd


format:
  html:
    theme: sandstone
    css: theme.scss
    page-layout: full

comments:
  giscus:
    repo: vuqv/vuqv.github.io